### ISSUE TITLE
I'm not seeing CodeBuild logs in my terminal while deploying

### ISSUE THREAD

**Issue by ethanwe** [DaySmart/frankenstack#34]
I'm pretty sure the logs from CodeBuild are supposed to be showing up in my terminal when I deploy something, but I'm not seeing any of them.

**Comment by mberryman-daysmart** [comment]
Seconded! We used to see the logs that are showing in CodeBuild in the terminal when we deployed via "serverless deploy".  Now we need to go watch the logs in CodeBuild to get information about compilation or deploy errors.

**Comment by Shereef** [comment]
This has been since fixed
